### ISSUE TITLE
Proper Directory structure

### ISSUE THREAD

**Issue by aayusharora** [Small-Start/Hospital#5]
There should be a proper directory structure 
                HOSPITAL 
                         /MainHospital 
                                            1.  /views
                                            2.  /JS
                                            3.  /CSS
                         /PrimaryHospital
                                             1. /views
                                             2.  /JS
                                             3. /CSS
                   The views will contain all php files .

**Comment by ankitjain28may** [comment]
can you please elaborate this?

**Comment by aayusharora** [comment]
@ankitjain28may ,The files are not clubbed according to their type.All JS,CSS,HTML files must be grouped into respective folders,as mentioned above .
There will be two folders , main hospital and primary hospital.
In both of them , There will be three folders JS,CSS,Views

**Comment by ankitjain28may** [comment]
ok..!!

**Comment by aayusharora** [comment]
@ankitjain28may ,Do you like to work on it ?

**Comment by ankitjain28may** [comment]
Yupp !!

**Comment by aayusharora** [comment]
@ankitjain28may ,go for it :)

**Comment by aayusharora** [comment]
@ankitjain28may , Whats the status?

**Comment by ankitjain28may** [comment]
I have done the part of main hospital, as i am volunteer in zealicon so i wont get much time these days but after zealicon, i will complete it.

**Comment by ankitjain28may** [comment]
All files must be in a views or outside the views??

**Comment by aayusharora** [comment]
@ankitjain28may , views is a seperate folder like js ,css  which contains .php files

**Comment by ankitjain28may** [comment]
OKk

**Comment by aayusharora** [comment]
@ankitjain28may ,status?

**Comment by ankitjain28may** [comment]
still working..!!

**Comment by aayusharora** [comment]
Thanks @ankitjain28may ankit
